version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Commit
          command: git config --global user.email "lucaschev17@gmail.com"
      - run:
          name: Commit
          command: git config --global user.name "Lucaschev17"
      - run:
          name: Commit
          command: git add .
      - run:
          name: Commit
          command: git commit -m "Contentful update"
      - run:
          name: Deploy
          command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules